services:
  - type: web
    name: anyprint-backend
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn tshirt_store.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: anyprint-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://anyprint-prototype-frontend.onrender.com"
      - key: WEB_CONCURRENCY
        value: 4

databases:
  - name: anyprint-db
    databaseName: anyprint
    user: anyprint_user
