# Generated by Django 4.2.16 on 2026-04-21 04:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.text import slugify


def _default_colors(product):
    style = (getattr(product, 'print_style', '') or '').lower()
    category_name = (product.category.name if product.category_id and product.category else '').lower()

    if 'graphic' in style or 'graphic' in category_name:
        return ['Black', 'Cream', 'Navy']
    if 'kids' in style or 'kids' in category_name:
        return ['White', 'Sky', 'Mint']
    if 'street' in style or 'oversized' in category_name:
        return ['Black', 'Sand', 'Olive']
    if 'minimal' in style:
        return ['Black', 'White', 'Stone']
    return ['Black', 'White', 'Sand']


def forwards(apps, schema_editor):
    Product = apps.get_model('shop', 'Product')
    ProductVariant = apps.get_model('shop', 'ProductVariant')
    User = apps.get_model(settings.AUTH_USER_MODEL.split('.')[0], settings.AUTH_USER_MODEL.split('.')[1])
    UserProfile = apps.get_model('shop', 'UserProfile')
    Order = apps.get_model('shop', 'Order')
    OrderStatusEvent = apps.get_model('shop', 'OrderStatusEvent')

    for product in Product.objects.all():
        if ProductVariant.objects.filter(product_id=product.id).exists():
            continue

        colors = _default_colors(product)
        sizes = ['S', 'M', 'L', 'XL']
        combinations = [(size, color) for size in sizes for color in colors]
        total_stock = int(product.stock_quantity or 0)
        base_stock = total_stock // len(combinations) if combinations else 0
        remainder = total_stock % len(combinations) if combinations else 0

        for index, (size, color) in enumerate(combinations):
            variant_stock = base_stock + (1 if index < remainder else 0)
            ProductVariant.objects.create(
                product_id=product.id,
                size=size,
                color=color,
                stock_quantity=variant_stock,
                sku=slugify(f'{product.slug}-{size}-{color}'),
                is_active=True,
            )

    for user in User.objects.all():
        role = 'OWNER' if user.is_superuser else 'ADMIN' if user.is_staff else 'USER'
        UserProfile.objects.get_or_create(user_id=user.id, defaults={'role': role, 'display_name': ''})

    for order in Order.objects.all():
        if not order.tracking_number:
            order.tracking_number = f'AP-{order.id:06d}'
            order.save(update_fields=['tracking_number'])

        if not OrderStatusEvent.objects.filter(order_id=order.id).exists():
            OrderStatusEvent.objects.create(order_id=order.id, status='PENDING', note='Legacy order migrated.')


def backwards(apps, schema_editor):
    ProductVariant = apps.get_model('shop', 'ProductVariant')
    UserProfile = apps.get_model('shop', 'UserProfile')
    OrderStatusEvent = apps.get_model('shop', 'OrderStatusEvent')
    ProductVariant.objects.all().delete()
    UserProfile.objects.all().delete()
    OrderStatusEvent.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0003_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bundle_discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_delivery_days',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('PACKED', 'Packed'), ('SHIPPED', 'Shipped'), ('OUT_FOR_DELIVERY', 'Out for delivery'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='subtotal_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=40, unique=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='color',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='product',
            name='print_style',
            field=models.CharField(choices=[('Classic', 'Classic'), ('Minimal', 'Minimal'), ('Graphic', 'Graphic'), ('Street', 'Street'), ('Kids', 'Kids')], default='Classic', max_length=40),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to='shop.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Admin'), ('USER', 'User')], default='USER', max_length=10)),
                ('display_name', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('discount_type', models.CharField(choices=[('PERCENT', 'Percent'), ('FIXED', 'Fixed amount')], default='PERCENT', max_length=10)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('minimum_subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('active', models.BooleanField(default=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('first_order_only', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applies_to_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.category')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('2XL', '2XL')], max_length=4)),
                ('color', models.CharField(max_length=40)),
                ('sku', models.CharField(max_length=80, unique=True)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='shop.product')),
            ],
            options={
                'ordering': ['product__name', 'size', 'color'],
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('title', models.CharField(blank=True, max_length=120)),
                ('comment', models.TextField(blank=True)),
                ('is_approved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='shop.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('PACKED', 'Packed'), ('SHIPPED', 'Shipped'), ('OUT_FOR_DELIVERY', 'Out for delivery'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], max_length=20)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_events', to='shop.order')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='shop.promocode'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='shop.productvariant'),
        ),
        migrations.AddConstraint(
            model_name='wishlistitem',
            constraint=models.UniqueConstraint(fields=('user', 'product'), name='unique_wishlist_item'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('product', 'size', 'color'), name='unique_product_variant'),
        ),
        migrations.AddConstraint(
            model_name='productreview',
            constraint=models.UniqueConstraint(fields=('product', 'user'), name='unique_product_review_per_user'),
        ),
        migrations.RunPython(forwards, backwards),
    ]
